### PR TITLE
Add new methods to delete likes and edit the message of posts and comments

### PR DESCRIPTION
**Pull request by joausaga**
Add three new methods:
1- Delete likes of an object (post or comment)
2- Edit the message of a post
3- Edit the message of a comment

### CODE REVIEW

**Comment by martey** [comment]
Would it be possible for you to add tests and fix the PEP8 issues that caused Travis to fail?

**Comment by joausaga** [comment]
Hi martey, I fixed PEP8 issues and added test cases to test the new functions. I assumed that facebook-sdk is associated to facebook app that has posting permissions but it seems the function to get the access token fails to return a valid app access token. 

Do you know what is this error about 'An active access token must be used to query information about the current user.' ?

**Comment by martey** [comment]
> I assumed that facebook-sdk is associated to facebook app that has posting permissions but it seems the function to get the access token fails to return a valid app access token.

I think it is returning a valid application access token, but that you need a [page token](https://developers.facebook.com/docs/facebook-login/access-tokens#pagetokens) to use `put_wall_post`.

I've re-reviewed your changes (I only glanced at them before) and have some thoughts:

 - `edit_post` and `edit_comment` are one line functions that **contain the exact same code**. At the very least, they should be combined in one `edit_object` function, but since the code is so simple, I think this work better as an example in the documentation than an additional function.
 - The docstring and name of the `delete_likes_object` function are both sort of confusing (Does the function delete all likes from the object, or just unlike the object if the user has previously liked it?). Again, since this is only one line of code (and extremely similar to the existing `delete_object` function), wouldn't it make more sense as a documentation example?

**Comment by joausaga** [comment]
Agreed with your first suggestion and fixed the code accordingly.

Regarding the second thought, I think calling it delete_object will be confusing since it doesn't delete the object but the likes of the objects, so the name it has, I think, is more appropriate. The docstring is ambiguous as it is ambiguous Facebook documentation regarding this [function](https://developers.facebook.com/docs/graph-api/reference/v2.3/object/likes). I suppose it unlikes the object if the user has previously liked it but Facebook document doesn't say that so I putted exactly what I found in graph api doc.

Travis is still failing because I don't know how I can get a page toke from the environment FACEBOOK_APP_ID and FACEBOOK_SECRET variables. You haven't provided neither test cases for  publishing functions (put_wall_post for instance) so I don't have an example from where get inspired.

**Comment by joausaga** [comment]
hi martey, can we follow-up on this?, i'm really interested in making this happens

**Comment by martey** [comment]
Thanks for pinging me about this.

I still don't think you have made the case for why these need to be functions (since they are both only one line of code) instead of examples in the documentation.

**Comment by joausaga** [comment]
Ok, so, following this criterion it should be also removed the functions get_connections, get_object, and fql, and even some others that contains only two lines: one with a simple variable assignment and the other with a calling to the request method (e.g., get_objects), why are they there instead of just providing examples in the documentation? 

For me functions are also a matter of providing abstractions on top of common functionalities, such as editing the message of posts or deleting the likes of posts. With your reasoning we can just write a nice blog telling the people how to use the API of Facebook.

If you are not willing to include these functions is just fine for me just me let me know so i don't waste my time waiting for something that is not going to happen.

**Comment by lucasrangit** [comment]
The existing `put_like` function helped me so I think it's reasonable to add a `delete_like` function.

**Comment by martey** [comment]
> Ok, so, following this criterion it should be also removed the functions get_connections, get_object, and fql, and even some others that contains only two lines: one with a simple variable assignment and the other with a calling to the request method (e.g., get_objects), why are they there instead of just providing examples in the documentation?

`get_connections`, `get_object`, and `fql` all date back to the code that Facebook originally produced. Removing them would break backwards compatibility for almost every single application that uses the SDK. Not adding your functions will not have the same ramifications.

> For me functions are also a matter of providing abstractions on top of common functionalities, such as editing the message of posts or deleting the likes of posts.

For me, functions in this library should either:

  - Be as generalized as possible. To use your earlier examples, `get_connections`, `get_object`, and `fql` are all general functions, working with the entire Graph API  - you can run `get_object` on a User, a Page, or a Post, and it will always work the same.

  - Make difficult functionality easy. Good examples of this are the `get_user_from_cookie` and `parse_signed_request` functions.

> If you are not willing to include these functions is just fine for me just me let me know so i don't waste my time waiting for something that is not going to happen.

I was hoping that you would update your pull request with commits that would create documentation examples, which would be easier to merge.

As it stands, even if my above objections were no longer valid, there are still multiple other issues that would be fixed because the code could be merged:

  - `edit_object` is a bad name for a function that only edits an object's `message` attribute
  - `delete_likes_object` has a bad function name and docstring. @lucasrangit's suggestion of calling it `delete_like` (to match with `put_like`) is a good one.

To be clear, I still think we would be best served by adding this information in the documentation.

**Comment by joausaga** [comment]
> get_connections, get_object, and fql all date back to the code that Facebook originally produced. Removing them would break backwards compatibility for almost every single application that uses the SDK. Not adding your functions will not have the same ramifications.

I only cite some examples of one/two-lines functions you have in the code as a way to show you that they are already in the code and are, from my point of view, perfectly valid

> I was hoping that you would update your pull request with commits that would create documentation examples, which would be easier to merge.

Why shouldn't you mention this before?, should I imagine it? I'll happily do it. In other projects I've contributed in only the main maintainers touch the documentation.

> As it stands, even if my above objections were no longer valid, there are still multiple other issues that would be fixed because the code could be merged:

Which are the 'multiple' other issues?, you have only mentioned two. Be more precise and let me know all of them so I can work to fix them. 

I think the SDK is still missing functions to edit properties of the objects. Maybe I haven't approach this limitation in the perfect way but I'm always open to receive suggestions.

**Comment by martey** [comment]
> Why shouldn't you explicitly mention it before? In other projects I've contributed in only the main maintainers touch the documentation.

This is not the case in this project. You (or anyone else) should feel free to submit pull requests improving the documentation.

> Which are the 'multiple' other issues?, you have only mentioned two. Be more precise and let me know all of them so I can work on fixing them.

As I have mentioned before, the primary issue with this pull request is that the functions it creates are too simple and derivative of existing functions. Fixing the other issues in the code will not change this or make me more likely to merge this code.

I can leave this pull request open in case you want to update the documentation. Otherwise, I am okay with you closing it.

**Comment by martey** [comment]
Closing this, per my earlier comments:

> As I have mentioned before, the primary issue with this pull request is that the functions it creates are too simple and derivative of existing functions. Fixing the other issues in the code will not change this or make me more likely to merge this code.

**Pull request closed without merging**
