### PR TITLE
Hi, it's nice to have error type(original code), in case it will be handled in details.

### PR DESCRIPTION
**Pull request by darnes**

### CODE REVIEW

**Comment by martey** [comment]
What if an error has a `message`, but no `code`? Could you use [.get](https://docs.python.org/2/library/stdtypes.html#dict.get) to avoid the KeyError that would otherwise happen?

**Comment by darnes** [comment]
you absolutely right, just was trying to follow available style. In that case it make sense to change all the code that reads exception details. I'll dial with it and come back later.

**Comment by martey** [comment]
No worries - I know #138 should fix most of our error handling issues, but any improvement (like this issue) would be great.

**Comment by martey** [comment]
Closing, but feel free to open a new pull request with additional changes.

**Pull request closed without merging**
